version: '2'
services:
  reverse_proxy:
    build:
      context: ./nginx
    container_name: reverse_proxy
    environment:
      - TZ=America/Los_Angeles
    ports:
      - 80:8080
      - 443:8443
    networks:
      - default
      - public
    restart: unless-stopped
    
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=4000
      - GUID=4000
      - TZ=America/Los_Angeles
    ports:
      - 1900:1900
    volumes:
      - jellyfin_config:/config
      #/pathtomedia:/data
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

volumes:
  jellyfin_config:

networks:
  default:
  public:
